[build]
  #ignore = "node ignore_build.js"
  publish = "_site"
  command = "npm run build"

# POST BUILD OPTIMIZATIONS
[build.processing]
  skip_processing = true

# NETLIFY PLUGINS
[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "_site/img", # Eleventy-Image Disk Cache
      ".cache" # Remote Asset Cache (not used currently)
    ]