const htmlmin = require('html-minifier');
const isProduction = process.env.NODE_ENV === 'production';

module.exports = (eleventyConfig) => {
  eleventyConfig.addTransform('htmlmin', function (content) {
    if (
      this.page.outputPath &&
      this.page.outputPath.endsWith('.html') &&
      isProduction
    ) {
      return htmlmin.minify(content, {
        collapseBooleanAttributes: true,
        collapseWhitespace: true,
        decodeEntities: true,
        includeAutoGeneratedTags: false,
        removeComments: true,
      });
    }

    return content;
  });
};
